export enum PlaceholderEntityTemplateEnum {
  CUSTOMERS = 'CUSTOMERS',
  TRANSACTIONS = 'TRANSACTIONS',
  PRODUCTS = 'PRODUCTS',
  TOP_PRODUCTS = 'TOP_PRODUCTS',
  REPORTS = 'REPORTS',
  SALES_AGENTS = 'SALES_AGENTS',
  LOGIN = 'LOGIN'
}
