version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Restoring packages..."
      - dotnet restore Beelina.API/Beelina.API.csproj

  build:
    commands:
      - echo "Building the project..."
      - dotnet build Beelina.API/Beelina.API.csproj --configuration Release --no-restore

  post_build:
    commands:
      - echo "Publishing as self-contained for linux-x64..."
      - dotnet publish Beelina.API/Beelina.API.csproj --configuration Release --runtime linux-x64 --self-contained true --output ./publish -p:PublishTrimmed=false
      - echo "Creating Procfile..."
      - echo "web: ./Beelina.API" > ./publish/Procfile
      - echo "Setting execute permissions on binary..."
      - chmod +x ./publish/Beelina.API
      - echo "Zipping published output for Elastic Beanstalk..."
      - cd publish
      - zip -r ../BeelinaAPI.zip .
      - cd ..

artifacts:
  files:
    - BeelinaAPI.zip
