version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Restoring packages..."
      - dotnet restore Beelina.API/Beelina.API.csproj

  pre_build:
    commands:
      - echo "Running unit tests..."
      - dotnet test Beelina.UnitTest/Beelina.UnitTest.csproj --configuration Release --no-restore --logger:trx
      # Optional: Stop pipeline on test failure
      - echo "Unit tests passed."

  build:
    commands:
      - echo "Building..."
      - dotnet build Beelina.API/Beelina.API.csproj --configuration Release --no-restore

  post_build:
    commands:
      - echo "Publishing..."
      - dotnet publish Beelina.API/Beelina.API.csproj --configuration Release --runtime linux-x64 --self-contained true -p:IncludeAllContentForSelfExtract=true --output ./publish

      - echo "Creating Procfile..."
      - echo "web:./BeelinaAPI" > ./publish/Procfile
      - chmod +x ./publish/BeelinaAPI

artifacts:
  files:
    - '**/*'
  base-directory: publish
  discard-paths: yes
