name: Continuous integration for Reserbiz Backend

on:
  push:
    branches: [master, development]
    paths:
      [
        .github/workflows/**,
        ReserbizAPP.API/**,
        ReserbizAPP.Hangfire/**,
        ReserbizAPP.LIB/**,
        ReserbizAPP.Tests/**,
        ReserbizAPP.IntegrationTests/**,
      ]

  pull_request:
    branches: [master, development]
    paths:
      [
        .github/workflows/**,
        ReserbizAPP.API/**,
        ReserbizAPP.Hangfire/**,
        ReserbizAPP.LIB/**,
        ReserbizAPP.Tests/**,
        ReserbizAPP.IntegrationTests/**,
      ]

jobs:
  build:
    name: Build and Test Reserbiz backend
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.402

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.0.0
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          
      - name: Clean Solution
        run: dotnet clean ReSerBiz.sln --configuration Release && dotnet nuget locals all --clear

      - name: Set Environment Variable
        run: |
          echo "ASPNETCORE_ENVIRONMENT=IntegrationTest" >> $env:GITHUB_ENV

      - name: Set up integration test databases
        shell: pwsh
        run: sqlcmd -i script.sql
        working-directory: ./ReserbizAPP.IntegrationTests

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Unit Test
        run: dotnet test ReserbizAPP.Tests --no-build --verbosity normal

      - name: Run Integration Test
        run: dotnet test
        working-directory: ./ReserbizAPP.IntegrationTests
